name: build

on: [push, pull_request]

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    # TODO: Remove --ignore-platform-reqs when we're on newer PHPUnit versions
    - run: composer install --ignore-platform-reqs
    - run: composer test
    - run: php vendor/bin/php-coveralls -v
